# Site settings
title: 맹개발의 블로그
url: "http://yunho0130.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  겸손하게 프로그래밍 하자

# Your information
email: yunho0130@gmail.com
author: 맹개발
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: One sentence introducing yourself.
#twitter_username: twitter_username
github_username:  yunho0130

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: maengdev   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
